import{createSignedReadUrl as P}from"@/lib/storage";import{formatZAR as Z}from"@/lib/format";const h=process.env.AIRTABLE_API_KEY,u="appMB4HF3PkGe2rZd",g="tblx9AkbkYzo8Cqhu",p="tblTYFnQ9cn7SNKXi",I="https://api.airtable.com/v0";async function f(e,i={}){const t=await fetch(`${I}/${e}`,{...i,headers:{Authorization:`Bearer ${h}`,"Content-Type":"application/json",...i.headers}});if(!t.ok){const n=await t.text().catch(()=>"");throw new Error(`Airtable ${i.method||"GET"} ${e} failed: ${t.status} ${n}`)}return t.json()}function l(e){return String(e||"").trim().replace(/\s+/g," ").toLowerCase()}function d(e,i){if(!i)return null;const t=l(i);return e.find(r=>l(r)===t)||null}const DEVICE_BRAND_CHOICES=["Apple","Samsung","Sony","Microsoft","Nintendo","Steam","Lenovo","Asus","Acer","Dell","HP","MSI","Razer","Google","Huawei","Honor","Oppo","Vivo","Xiaomi","Redmi","OnePlus","Nothing","CMF by Nothing","LG","HTC","Meta","Garmin","GoPro","Beats","Bose","Sonos","Canon","Logitech","Hisense","Philips","Siemens","Nespresso","WD","Other"];
/**
 * Airtable's "Device Brand (Select)" is a single-select: it needs exactly one
 * string. The site's brand_filter is a LIST (sellyourconsole carries six), and
 * handing that list straight to Airtable is what made every lead write 422 with
 * INVALID_VALUE_FOR_COLUMN from 23 Aug 2026 until this was fixed -- silently,
 * because the sync runs inside after().
 *
 * The device's own catalogue brand is the right answer. The site's filter is
 * only a fallback, and only when it names exactly one brand, because on a
 * multi-brand site it says nothing about which brand THIS device is.
 * Anything that isn't a real choice on the field is dropped rather than sent:
 * an unknown string 422s the whole batch, and the brand is already carried in
 * "Device Model (Text)" and the Models Strict link.
 */
function resolveDeviceBrand(itemBrand,siteBrands){const fromSite=Array.isArray(siteBrands)?(siteBrands.length===1?siteBrands[0]:null):siteBrands;const raw=String(itemBrand||fromSite||"").trim();if(!raw)return null;const match=d(DEVICE_BRAND_CHOICES,raw);if(!match)console.warn(`airtable: "${raw}" is not a choice on Device Brand (Select), leaving the brand blank on this record. Add it to the Airtable field and to DEVICE_BRAND_CHOICES to start recording it.`);return match}
const B=["Sealed","Mint","Good","Poor"],O="Default (EFT)",m="Epic Deals Consignment (10% Extra)",S="Epic Deals Voucher (12% Extra!) - Spend it in our online store",b={10:"Epic Deals Consignment (10% Extra)"},A={12:"Epic Deals Voucher (12% Extra!) - Spend it in our online store",5:"Epic Deals Voucher (5% Extra)"},y={"first national bank (fnb)":"First National Bank (FNB)",absa:"ABSA",capitec:"Capitec",nedbank:"Nedbank",discovery:"Discovery",investec:"Investec","standard bank":"Standard Bank",other:"Other (Please Specify)"},_=["Cheque","Current","Savings","Other","Credit"],D=["Gauteng","Free State","Eastern Cape","KwaZulu-Natal","Limpopo","Mpumalanga","Northern Cape","North West","Western Cape"];function w(e){return d(B,e)}function $(e,i){if(e==="eft")return O;const t=i==null?null:Math.round(Number(i)),n=Number.isFinite(t)?t:null;return e==="consignment"?n!=null&&b[n]?b[n]:(n!=null&&console.warn(`airtable: no known Consignment Airtable choice for ${n}%, falling back to "${m}". If the cockpit rate changed, add it to CONSIGNMENT_CHOICES_BY_PCT once the matching Airtable choice exists.`),m):e==="voucher"?n!=null&&A[n]?A[n]:(n!=null&&console.warn(`airtable: no known Voucher Airtable choice for ${n}%, falling back to "${S}". If the cockpit rate changed, add it to VOUCHER_CHOICES_BY_PCT once the matching Airtable choice exists.`),S):null}function v(e){return e&&(y[l(e)]||d(Object.values(y),e))||null}function k(e){return d(_,e)}function R(e){return d(D,e)}function C(e){return e?"Yes":"No"}function E(e){return String(e).replace(/"/g,'\\"')}async function N({brand:e,modelName:i}){const t=E(l(i)),n=await f(`${u}/${p}?`+new URLSearchParams({filterByFormula:`AND(LOWER(TRIM({Name}))="${t}", LOWER(TRIM({Brands}))="${E(l(e))}")`,maxRecords:"1"}));if(n.records?.length)return n.records[0].id;const r=await f(`${u}/${p}?`+new URLSearchParams({filterByFormula:`LOWER(TRIM({Name}))="${t}"`,maxRecords:"1"}));return r.records?.length?r.records[0].id:null}const MODEL_NAME_FILLER=new Set(["only","edition","version","inch","in","the","with","and"]);
/**
 * Models Strict is an externally synced table that names things its own way:
 * "PlayStation 5 (Digital Edition)" where we say "PlayStation 5 Digital",
 * "iPad Air 5th Gen (Wi-Fi Only)" where we say "iPad Air 5th Gen WiFi",
 * "Steam Deck (LCD Version)" where we say "Deck LCD". Exact matching missed
 * every one of those.
 *
 * Reducing both sides to a set of meaningful words -- punctuation and bracketed
 * qualifiers dropped, Wi-Fi spellings unified, the brand folded in so a bare
 * "Deck LCD" can still reach "Steam Deck" -- lines them up. Order stops
 * mattering too, which is what rescues 'iPad Pro 13 M4 WiFi' against
 * 'iPad Pro M4 13" (Wi-Fi Only)'.
 */
function canonicalModelKey(name,brand){const words=e=>String(e||"").toLowerCase().replace(/wi[-\s]?fi/g,"wifi").replace(/[^a-z0-9]+/g," ").split(" ").filter(Boolean);const meaningful=words(name).filter(w=>!MODEL_NAME_FILLER.has(w));if(meaningful.length===0)return"";return[...new Set([...words(brand),...meaningful])].sort().join(" ")}
/**
 * Only ever returns a UNIQUE hit. Several Strict rows can reduce to the same
 * words -- the Apple Watch variants do, since they differ only by case material
 * and GPS -- and linking a lead to the wrong model is worse than leaving the
 * cell empty.
 */
async function findModelByCanonicalName({brand:e,modelName:i}){const target=canonicalModelKey(i,e);if(!target)return null;const tokens=String(i||"").toLowerCase().replace(/[^a-z0-9]+/g," ").split(" ").filter(w=>w.length>=3&&w!=="wifi"&&!MODEL_NAME_FILLER.has(w)).slice(0,2);if(tokens.length===0)return null;const clauses=tokens.map(t=>`SEARCH("${E(t)}", LOWER({Name}))`);e&&clauses.unshift(`LOWER(TRIM({Brands}))="${E(l(e))}"`);const formula=clauses.length>1?`AND(${clauses.join(", ")})`:clauses[0];const matches=new Map();let offset=null;for(let page=0;page<3;page++){const params=new URLSearchParams({filterByFormula:formula,pageSize:"100"});offset&&params.set("offset",offset);const res=await f(`${u}/${p}?`+params);for(const rec of res.records||[])canonicalModelKey(rec.fields?.Name,rec.fields?.Brands)===target&&matches.set(rec.id,rec.fields?.Name);if(!res.offset)break;offset=res.offset}if(matches.size===1)return[...matches.keys()][0];matches.size>1&&console.warn(`airtable: "${i}" reduces to the same words as ${matches.size} Models Strict rows (${[...matches.values()].join(", ")}), leaving the link blank rather than guessing`);return null}
async function L({brand:e,modelName:t}){if(!t)return null;const exact=await N({brand:e,modelName:t});if(exact)return exact;const near=await findModelByCanonicalName({brand:e,modelName:t});if(near)return near;console.warn(`airtable: no Models Strict row matches "${t}"${e?` (${e})`:""}, leaving "Stated Device Model (Strict)" blank. That table is externally synced, so this app cannot create the missing row; add it at the source if the link matters.`);return null}async function T(e){if(!e)return null;try{return[{url:await P(e)}]}catch(i){return console.error(`airtable: could not create signed read URL for ${e}`,i),null}}function F(e){const i=String(e.fullName||"").trim().split(/\s+/),t=i[0]||"",n=i.slice(1).join(" "),r={"Status Select":"A1 - Awaiting Arrival","Submission Type":"Courier Collection","Client First Name":t,"Client Surname":n,"Client Phone Number":e.phone,"Website Sent From":e.siteDomain};e.email&&(r["Client Email"]=e.email),e.address&&(r["Client Street Number and Name"]=e.address),e.suburb&&(r["Client Suburb"]=e.suburb),e.city&&(r["Client City"]=e.city);const o=R(e.province);o&&(r["Client Province"]=o),e.idNumber&&(r["Client ID Number"]=e.idNumber),e.preferredCollectionDate&&(r["Collection / Drop Off Date"]=e.preferredCollectionDate),r["Collection=Residential?"]=C(e.residentialAddress),r["T's and C's Agreement?"]=C(e.termsAccepted),r["Privacy Policy Agreement?"]=C(e.privacyAccepted),r["Legal Owner?"]=C(e.ageConfirmed),e.couponCode&&(r["SY Voucher / Coupon"]=e.couponBonus?`${e.couponCode} (+${Z(e.couponBonus)} on this order)`:e.couponCode);const a=v(e.bankName);a&&(r["Bank Name (Client)"]=a),e.accountNumber&&(r["Bank Account Number (Client)"]=e.accountNumber);const c=k(e.accountType);return c&&(r["Bank Account Type (Client)"]=c),e.branchCode&&(r["Client Bank Branch Code"]=e.branchCode),r}async function M(e,i){const brand=resolveDeviceBrand(e.brand,i);const t={Source:e.airtableSource,"Device Model (Text)":e.model};brand&&(t["Device Brand (Select)"]=brand);const n=w(e.condition);n&&(t["Stated Condition"]=n);const r=$(e.paymentPreference,e.paymentBonusPct);r&&(t["Payment Preference"]=r);const o=e.capacity;o&&(t["Stated Capacity"]=o),e.accessories?.length&&(t["Accessories Included"]=e.accessories.map(c=>c.label).join(", ")),e.faultDescription&&(t["Client Reported Issue (App)"]=e.faultDescription);const a=(e.faultDeductionTotal||0)+(e.aiFaultDeductionTotal||0);t["Quoted Value"]=Math.round((e.price+(e.accessoryBonusTotal||0)-a)*100)/100;try{const c=await L({brand:brand||"",modelName:e.model});c&&(t["Stated Device Model (Strict)"]=[c])}catch(c){console.error(`airtable: model matching failed for "${e.model}"`,c)}return t}function x(e,i){const t=[];for(let n=0;n<e.length;n+=i)t.push(e.slice(n,n+i));return t}
/**
 * One unparseable cell used to take the entire lead down with it: the write
 * throws, and because the whole sync runs inside after() nobody sees it -- the
 * customer gets a success screen and ops never gets the lead. That is exactly
 * how four days of submissions went missing in Aug 2026.
 *
 * When Airtable names the column it could not parse, drop that one field and
 * write the lead again. A record with one blank cell is recoverable; a lead
 * that never arrives is not. Retried once only, and the failure is logged
 * loudly either way.
 */
async function postLeadRecords(records){try{return await f(`${u}/${g}`,{method:"POST",body:JSON.stringify({records})})}catch(err){const m=/Cannot parse value for field (.+?)"/.exec(String(err?.message||""));const bad=m&&m[1];if(!bad||!records.some(r=>bad in r.fields))throw err;console.error(`airtable: Airtable could not parse "${bad}", rewriting this lead without that field so it still lands`,err);const stripped=records.map(r=>{const fields={...r.fields};delete fields[bad];return{...r,fields}});return f(`${u}/${g}`,{method:"POST",body:JSON.stringify({records:stripped})})}}export async function syncLeadToAirtable({lead:e,items:i,brand:t}){if(!h){console.warn("airtable: AIRTABLE_API_KEY not set, skipping Airtable sync");return}const[n,r]=await Promise.all([T(e.idDocumentPath),T(e.selfiePath)]),o=F(e);n&&(o["Client ID Doc"]=n),r&&(o["Client Photo"]=r);const c=(await Promise.all(i.map(s=>M({...s,airtableSource:e.airtableSource,paymentPreference:e.paymentPreference,paymentBonusPct:e.paymentBonusPct},t)))).map(s=>({fields:{...o,...s}}));for(const s of x(c,10))await postLeadRecords(s)}